import type { Metadata } from "next"

import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'
import { cn } from '@/lib/utils'
import { Raleway } from "next/font/google"
import "./globals.css"


const fontSans = Raleway({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#53067A] font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
